# Generated by Django 4.2.6 on 2023-11-30 15:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlist',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='items',
        ),
        migrations.AddField(
            model_name='eventlist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='location',
            field=models.TextField(default='location', max_length=100),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='title',
            field=models.TextField(default='name of event', max_length=100),
        ),
    ]
