# Generated by Django 4.2.6 on 2023-12-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_eventlist_complete_remove_eventlist_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='location',
            field=models.CharField(default='event location', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='title',
            field=models.CharField(default='name of event', max_length=100),
        ),
    ]
